name: deploy-central

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Setup Maven settings
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>oss1</id>
                <username>${{ secrets.CENTRAL_USERNAME }}</username>
                <password>${{ secrets.CENTRAL_PASSWORD }}</password>
              </server>
            </servers>
            <!-- 中央仓库 -->
            <profiles>
              <profile>
                <id>deploy-central</id>
                <properties>
                  <altReleaseDeploymentRepository>
                    oss1::default::https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2
                  </altReleaseDeploymentRepository>
                  <altSnapshotDeploymentRepository>
                    oss1::default::https://ossrh-staging-api.central.sonatype.com/content/repositories/snapshots
                  </altSnapshotDeploymentRepository>
                </properties>
              </profile>
            </profiles>
          </settings>
          EOF

      - name: Configure GPG
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gnupg

      - name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build with Maven
        env:
          GPG_KEYNAME: ${{ steps.import-gpg.outputs.fingerprint }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: mvn clean deploy -P release,deploy-central
